site_name: Otter Browser Documentation
theme_dir: theme
site_favicon: favicon.ico
site_description: Otter Browser documentation
site_author: Otter Browser Team
copyright: © <a href="http://otter-browser.org">Otter Browser Team</a>
use_directory_urls: false
pages:
- Home: index.md
- Basic features:
  - "Bookmarks": basic/bookmarks.md
  - "History": basic/history.md
  - "Startup configuration": basic/startup-configuration.md
  - "Speed dial": basic/speed-dial.md
  - "Search engines": basic/search-engines.md
- Advanced features:
  - "Command line": advanced/command-line.md
- Customisation:
  - "Built-in customisation": customisation/built-in-customisation.md
  - "Extensions": customisation/extensions.md
  - "User scripts": customisation/user-scripts.md
  - "User styles": customisation/user-styles.md
- Bugs and features: report-issue.md
- Frequently asked questions: faq.md
