site_name: Otter Browser Documentation
site_favicon: favicon.ico
site_description: Otter Browser documentation
copyright: © Otter Browser Team
pages:
- Home: "index.md"
- User Guide:
  - "Command Line": command-line.md
- Bugs and Features: report-issue.md